# Site settings
title: PRML

email: "dowkkr94@gmail.com"
url: "http://hyunahOh.github.io"
github_url: "http://github.com/hyunahOh/prml"
github_editurl: "/blob/gh-pages"
github_profile: "http://github.com/hyunahOh"
baseurl: "/prml"
disqus_shortname: hyunahOh

exclude:
  - README.md
  - _site
  
highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
